version: '3.4'

services:
  zyf2emonitorvue:
    image: zyf2emonitorvue
    build:
      context: packages/vue
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
